---
title: "Storybook Habituation Paradigm Data Analysis"
output:
  html_document:
    keep_md: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    df_print: paged
    theme: united
    highlight: tango
---

```{r echo=F}
d <- read.csv('dev_modals_data.csv')
d$age_group <- factor(d$age_group, levels=c('child', 'adult'))
d$age_group <- relevel(d$age_group, ref='child')
d$prob.label <- ordered(d$prob.label, levels=c('20%\nProbability', '80%\nProbability', '100%\nProbability'))
```

# Participants
```{r echo=F}
source('modals-resource.R')
d %>%
    distinct(partID, .keep_all=T) %>%
    group_by(age_group) %>%
    dplyr::summarize(N=n(),
            mean = mean(age),
            min  = min(age),
            max  = max(age),
            sd   = sd(age),
            ci.low = mean - ci.low(age),
            ci.hi  = mean + ci.high(age)) %>%
  kable(., caption='Gen. 2 Participant Demographics', align='c') %>%
kable_styling(., "striped", full_width = F)

d %>%
    distinct(partID, .keep_all=T) %>%
    group_by(age_year) %>%
    dplyr::summarize(N=n(),
            mean = mean(age),
            min  = min(age),
            max  = max(age),
            sd   = sd(age),
            ci.low = mean - ci.low(age),
            ci.hi  = mean + ci.high(age)) %>%
  kable(., caption='Gen. 2 Participant Demographics by Age Group', align='c') %>%
kable_styling(., "striped", full_width = F)
```

# Modal Selection
```{r}
d %>%
  select(age_year, modal_pair, prob.label, can, could, should, will) %>%
  group_by(age_year, modal_pair, prob.label) %>%
  dplyr::summarise(can = mean(can),
                   could=mean(could),
                   should=mean(should),
                   will=mean(will)) %>%
  gather(modal, mean, -age_year, -modal_pair, -prob.label) %>%
  filter(mean > 0) %>%
  group_by(age_year, modal_pair, prob.label) %>%
  
  ggplot(., aes(x=modal_pair, y=mean, fill=modal)) +
    geom_bar(stat='identity') +
    geom_hline(yintercept=0.5, lty=2, color='gray10')+
    facet_grid(cols=vars(age_year), rows=vars(prob.label), drop=T, scales='free') +
    theme(strip.placement = 'outside',
          strip.background = element_rect(fill='white'),
          strip.text.x = element_text(family='serif', size=14, color='gray10'),
          strip.text.y = element_text(family='serif', size=12, color='gray10', angle = 0),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          axis.title=element_text(family='serif', size=14, color='gray10'),
          axis.text.x=element_text(family='serif', size=12, color='gray10', angle=60, hjust=1),
          panel.background = element_rect(fill='white'),
          panel.grid = element_blank(),
          plot.background = element_rect(fill='gray90', color='gray10'),
          legend.background = element_rect(fill='gray90'),
          legend.text = element_text(family='serif', size=12, color='gray10'),
          legend.title = element_text(family='serif', size=14, color='gray10'),
          plot.margin = margin(30, 10, 10, 20),
          plot.title = element_text(family='serif', size=14, color='gray10')) +
    scale_fill_manual(values=modal.colors,
                      name='Modal') +
  labs(x='Modal Pair', y='Mean Selection', title='Epistemic Modal Preference by Age and Outcome Probability')
```

```{r}

```

